p1 = Project.create(name: 'Profiling App')
p1.tasks.create(name: 'Initialize Application')
p1.tasks.create(name: 'Add rack mini profiler gem')
p1.tasks.create(name: 'Update page project index to see total tasks')
p1.tasks.create(name: 'View profiler results')
p1.tasks.create(name: 'Optimize')

p1 = Project.create(name: 'Mini Chat App')
p1.tasks.create(name: 'Initialize Application')
p1.tasks.create(name: 'Add faye-rails gem')
p1.tasks.create(name: 'Configure Faye server')
p1.tasks.create(name: 'Create Publisher')
p1.tasks.create(name: 'Create Subscriber')
p1.tasks.create(name: 'Create User interface')
